import { createCipheriv, createDecipheriv, randomBytes } from 'crypto';
import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const ALGORITHM = 'aes-256-gcm';
const KEY_LENGTH = 32;
const ENV_FILE = join(process.cwd(), '.env.local');

let cachedKey: Buffer | null = null;

function getKey(): Buffer {
  if (cachedKey) return cachedKey;

  let keyHex = process.env.ENCRYPTION_KEY;

  if (!keyHex) {
    keyHex = randomBytes(KEY_LENGTH).toString('hex');

    if (!process.env.VERCEL) {
      // 本地开发：写入 .env.local 持久化
      try {
        const line = `\nENCRYPTION_KEY=${keyHex}\n`;
        if (existsSync(ENV_FILE)) {
          writeFileSync(ENV_FILE, line, { flag: 'a' });
        } else {
          writeFileSync(ENV_FILE, `# Auto-generated by PostWizard\nDATABASE_URL="file:./dev.db"\n${line.trim()}\n`, 'utf-8');
        }
        console.log('[PostWizard] 已自动生成 ENCRYPTION_KEY 并写入 .env.local');
      } catch {
        console.warn('[PostWizard] 无法写入 .env.local，请手动添加以下配置：');
        console.warn(`ENCRYPTION_KEY=${keyHex}`);
      }
    } else {
      // Vercel：无法写文件，提醒用户去 Dashboard 设置
      console.warn('[PostWizard] ENCRYPTION_KEY 未设置，已临时生成。');
      console.warn(`请在 Vercel Dashboard → Settings → Environment Variables 中添加：`);
      console.warn(`ENCRYPTION_KEY=${keyHex}`);
      console.warn('否则每次冷启动后已保存的 API Key 将无法解密。');
    }

    process.env.ENCRYPTION_KEY = keyHex;
  }

  const key = Buffer.from(keyHex, 'hex');
  if (key.length !== KEY_LENGTH) {
    throw new Error(`ENCRYPTION_KEY 长度不正确，应为 ${KEY_LENGTH * 2} 个十六进制字符`);
  }
  cachedKey = key;
  return key;
}

export function encrypt(text: string): string {
  if (!text) return text;
  const key = getKey();
  const iv = randomBytes(16);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const encrypted = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
}

export function decrypt(encryptedData: string): string {
  if (!encryptedData || !encryptedData.includes(':')) return encryptedData;
  const key = getKey();
  const [ivHex, authTagHex, encryptedHex] = encryptedData.split(':');
  if (!ivHex || !authTagHex || !encryptedHex) {
    throw new Error('加密数据格式不正确');
  }
  const decipher = createDecipheriv(ALGORITHM, key, Buffer.from(ivHex, 'hex'));
  decipher.setAuthTag(Buffer.from(authTagHex, 'hex'));
  const decrypted = Buffer.concat([
    decipher.update(Buffer.from(encryptedHex, 'hex')),
    decipher.final(),
  ]);
  return decrypted.toString('utf8');
}

export function isEncrypted(data: string): boolean {
  if (!data || typeof data !== 'string') return false;
  return data.includes(':') && data.split(':').length === 3;
}

export function decryptSafe(data: string): string {
  if (!isEncrypted(data)) return data;
  try {
    return decrypt(data);
  } catch {
    return data;
  }
}
